plugins {
    id 'maven-publish'
}

allprojects {
    apply plugin: 'maven-publish'

    version = project.mod_version
    group = 'io.github.diamondstar_mods'

    repositories {
        mavenCentral()
        maven { url 'https://maven.fabricmc.net/' }
        maven { url 'https://maven.quiltmc.org/repository/release' }
        maven { url 'https://maven.quiltmc.org/repository/snapshot' }
    }

    // Java release version is set per subproject
}

subprojects {
    // Java release version is set per subproject
}
