name: Gradle Build

on:
  push:
    branches: [ fabric-1.21.7 ]
  pull_request:
    branches: [ fabric-1.21.7 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Gradle
        run: ./gradlew build