pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'LegacyFabric'
			url = 'https://repo.legacyfabric.net/maven/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'Minecraft-Command-Maker'
include 'server'
include 'client'
include 'quilt-server'
include 'quilt-client'
include 'server-legacy'
