plugins {
    id 'java-library'
    id 'net.neoforged.gradle.userdev' version '7.0.173'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name + "-1.21-neoforge"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

sourceSets {
    main {
        resources {
            srcDirs = ['src/main/resources']
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "net.neoforged:neoforge:${project.neoforge_version}"
    implementation "com.google.code.gson:gson:2.10.1"
    compileOnly "net.luckperms:api:5.4"
}

runs {
    configureEach {
        systemProperty 'forge.logging.markers', ''
        systemProperty 'forge.logging.console.level', 'info'
    }

    server {
        workingDirectory project.file('run')
    }
}

processResources {
    inputs.property "version", project.version
    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": inputs.properties["version"]
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}
