buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://maven.neoforged.net/releases' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.neoforged.gradle:userdev:7.0.173'
        classpath 'net.minecraftforge.gradle:ForgeGradle:6.0.30'
    }
}

def useForge = project.hasProperty('forge')

if (useForge) {
    apply plugin: 'net.minecraftforge.gradle'
} else {
    apply plugin: 'net.neoforged.gradle.userdev'
}

apply plugin: 'java-library'

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name + (useForge ? "-1.21-forge" : "-1.21-neoforge")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

sourceSets {
    main {
        resources {
            srcDirs = ['src/main/resources']
        }
    }
}

repositories {
    mavenCentral()
}

if (useForge) {
    minecraft {
        mappings channel: 'official', version: project.minecraft_version
    }

    dependencies {
        minecraft "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"
        implementation "com.google.code.gson:gson:2.10.1"
        compileOnly "net.luckperms:api:5.4"
    }

    processResources {
        inputs.property "version", project.version
        filesMatching("META-INF/mods.toml") {
            expand "version": inputs.properties["version"]
        }
    }
} else {
    dependencies {
        implementation "net.neoforged:neoforge:${project.neoforge_version}"
        implementation "com.google.code.gson:gson:2.10.1"
        compileOnly "net.luckperms:api:5.4"
    }

    runs {
        configureEach {
            systemProperty 'forge.logging.markers', ''
            systemProperty 'forge.logging.console.level', 'info'
        }

        server {
            workingDirectory project.file('run')
        }
    }

    processResources {
        inputs.property "version", project.version
        filesMatching("META-INF/neoforge.mods.toml") {
            expand "version": inputs.properties["version"]
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}
