name: Bump Version

on:
  push:
    branches:
      - fabric-1.21.7

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version
        id: bump
        run: |
          if [ ! -f VERSION ]; then
            echo "1.0.0" > VERSION
          fi
          version=$(cat VERSION)
          IFS='.' read -r major minor patch <<< "$version"
          patch=$((patch + 1))
          if [ $patch -ge 10 ]; then
            patch=0
            minor=$((minor + 1))
          fi
          if [ $minor -ge 10 ]; then
            minor=0
            major=$((major + 1))
          fi
          new_version="$major.$minor.$patch"
          echo "$new_version" > VERSION
          git add VERSION
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Bump version to $new_version"
            git pull --rebase origin ${GITHUB_REF#refs/heads/}
            git push origin HEAD:${GITHUB_REF#refs/heads/}
          fi
