name: Build & Release with Gradle (auto-version)

on:
  push:
    branches:
      - fabric-1.21.7 # Change this to your main branch if needed

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Get and bump version
        id: version
        run: |
          if [ ! -f VERSION ]; then
            echo "1.0.0" > VERSION
          fi
          version=$(cat VERSION)
          IFS='.' read -r major minor patch <<< "$version"
          patch=$((patch + 1))
          if [ $patch -ge 10 ]; then
            patch=0
            minor=$((minor + 1))
          fi
          if [ $minor -ge 10 ]; then
            minor=0
            major=$((major + 1))
          fi
          new_version="$major.$minor.$patch"
          echo "$new_version" > VERSION
          echo "version=$new_version" >> $GITHUB_OUTPUT

      - name: Commit updated VERSION file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Bump version to ${{ steps.version.outputs.version }}"
          file_pattern: VERSION

      - name: Create Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag v${{ steps.version.outputs.version }}
          git push origin v${{ steps.version.outputs.version }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: build/libs/*.jar

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.version }}
          body: "Automated release for ${{ steps.version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
